---
# Target is device or group
# ansible-playbook update-device-url.yml -e "target=afspeelapparaat1 target_url=https://www.youtube.com/embed/<VIDEOID?autoplay=1"

# Update device/ group (afspeelapparaat)
- name: Update target URL
  hosts: "{{ target }}"
  become: true
  roles: 
    - role: update-device-url
  vars:
    target: "{{ target }}"
    target_url: "{{ target_url }}"
