---
# tasks file for update-device-url

# Update target URL
# python roles/update-device-url/files/update-device-url.py afspeelapparaat1 https://www.youtube.com/embed/db0A0Jt2Al4?autoplay=1
- name: Update device URL for {{ target }}
  script: update-device-url.py "{{ target }}" "{{ target_url }}"
  delegate_to: 127.0.0.1

# Deploy kiosk startup script from template
- name: Create kiosk startup script and make it executable
  template: 
    src: kiosk.j2
    dest: /home/picaster/kiosk.sh
    mode: '0755'

# Start kiosk.sh script as normal user (non elevated)
- name: Display the new page
  command: runuser -l picaster -c 'sh /home/picaster/kiosk.sh'
